languaje: node_js
node_js:
- 11.6.0
cache: npm
before_install:
install:
before_script:
script:
after_success:
after_failure:
after_script:
before_deploy:
deploy:
  provider: npm
    email: "arturo_gdev689x@outlook.com"
    api_key: "d8a7e2b7-5c28-4617-8c49-4bff9aeb6d56"
    on:
      branch: master
after_deploy: